[tools]
java = "latest"
just = "latest"
python = "latest"
shfmt = "latest"
"spm:kattouf/Sake" = "latest"
tuist = "latest"
xcbeautify = "latest"
xcodes = "latest"
yamllint = "latest"

[env]
_.python.venv = { path = "scripts/.venv", create = true }
